# Generated by Django 5.0 on 2023-12-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("art_name", models.CharField(max_length=50)),
                ("artist_name", models.CharField(max_length=50)),
                ("artist_country", models.CharField(max_length=50)),
                ("year_created", models.CharField(max_length=10)),
                ("museum", models.CharField(max_length=50)),
                ("museum_city", models.CharField(max_length=50)),
            ],
        ),
    ]
