# Generated by Django 5.0 on 2023-12-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="art_url",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
